# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RealmAutoIncrementalID' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for RealmAutoIncrementalID
  pod 'RealmSwift', '~>3.8'
end
